name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice
version: 0.2.3
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/flutter_google_places
maintainer: Kev Morelli (@KevMorelli)

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.0
  google_maps_webservice: ^0.0.14
  splashscreen:
  dio: 2.1.7
  shared_preferences: any
  url_launcher: ^5.0.2
  rflutter_alert: ^1.0.2
  http: ^0.12.0
  google_sign_in:
  google_maps_flutter:
  flutter_rating_bar: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
